name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
      runs-on: ubuntu-latest
      steps:
      - name: Testing workflow
        uses: actions/checkout@v2

      - name: Maven Test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:check

